# Generated by Django 5.2.3 on 2025-07-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('completed_on', models.DateField()),
                ('description', models.CharField(max_length=250)),
                ('certificate_url', models.CharField(max_length=100)),
            ],
        ),
    ]
